version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting install `date` . . .
      - VERSION="v2.9.0-beta.3"
      - curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/$VERSION/deployments/scripts/install.sh | bash -s latest-beta  

  build:
    commands:
      - echo Build started on `date`
      - docker -v
      - echo Scanning with horusec...
      - horusec start -p="./" -o="json" -O="./horusec.json"  || EXIT_CODE=$?

  post_build:
    commands:
      - echo Build completed on `date`
      - cat horusec.json
artifacts:
  files: horusec.json
